package uz.turgunboyevjurabek.rizon.madels.usersProfile

data class User(
    val address: String,
    val bonus_for_followers_status: Int,
    val collective_bonus_amount: Double,
    val coupon: Double,
    val date: String,
    val dateOfBirth: String,
    val debt: Double,
    val email: Any,
    val extra_bonus: Int,
    val first_name: String,
    val forMentorship: Int,
    val for_followers_status_percent: Double,
    val id: String,
    val last_name: String,
    val paid: Int,
    val passport: String,
    val personal_bonus: Double,
    val phoneNumTwo: String,
    val phone_number: String,
    val photo: String,
    val salary: Double,
    val stat_percent: Int,
    val user_id: Int,
    val user_score: Double,
    val user_status: String,
    val user_tree_score: Double,
    val user_tree_summa: Int,
    val warehouse: Warehouse
)